#!/usr/bin/env python3
"""Generate 49×31 procedural Pac-Man-style maze.

Strict no-dead-end rule:
- Cell is CORRIDOR if (col % 3 == 1) OR (row % 3 == 1)
- Else WALL.
This guarantees every corridor cell has >=2 corridor neighbours.

Plus overrides:
- Outer border wall (except tunnel row edges)
- Central ghost house at cols 21..27 rows 12..16
- Pac spawn at row 23 cols 23-25
- Tunnel row 14, ends open
- 4 energizers in corners
"""

COLS = 49
ROWS = 31

# Ghost house bounds (inclusive)
GH_X0, GH_X1 = 21, 27
GH_Y0, GH_Y1 = 12, 16

def in_ghost_house(x, y):
    return GH_X0 <= x <= GH_X1 and GH_Y0 <= y <= GH_Y1

def is_wall(x, y):
    # Outer border
    if y == 0 or y == ROWS - 1: return True
    if x == 0 or x == COLS - 1:
        return y != 14   # tunnel row keeps edges open
    # Tunnel row: walkable across (matches classic feel)
    if y == 14: return False
    # Inner pellet ring rows
    if y == 1 or y == ROWS - 2: return False

    # Ghost house carving
    if in_ghost_house(x, y):
        # Top wall except door at cols 23-25
        if y == GH_Y0:
            if 23 <= x <= 25: return False  # door cells
            return True
        if y == GH_Y1: return True              # bottom wall
        if x == GH_X0 or x == GH_X1: return True  # side walls
        return False                              # interior

    # Pac spawn cells walkable (row 23 cols 23-25)
    if y == 23 and 23 <= x <= 25: return False

    # Grid corridors
    col_corr = (x % 3 == 1)
    row_corr = (y % 3 == 1)
    return not (col_corr or row_corr)

def cell(x, y):
    # Tunnel marker on row 14 edges
    if y == 14 and (x <= 3 or x >= COLS - 4): return 'T'
    # Pac spawn marker
    if y == 23 and (x == 23 or x == 24 or x == 25): return 'P'
    # Ghost house door
    if y == GH_Y0 and (x == 23 or x == 24 or x == 25): return '-'
    # Ghost spawns
    if y == 14 and x == 22: return '1'
    if y == 14 and x == 24: return '2'
    if y == 14 and x == 25: return '3'
    if y == 14 and x == 27: return '4'
    # Corner energizers
    if (y == 3 or y == ROWS - 4):
        if x == 4 and not is_wall(x, y): return 'o'
        if x == COLS - 5 and not is_wall(x, y): return 'o'
    return '#' if is_wall(x, y) else '.'

rows = []
for y in range(ROWS):
    line = ''.join(cell(x, y) for x in range(COLS))
    assert len(line) == COLS, f"row {y} len {len(line)} != {COLS}"
    rows.append(line)

# Auto-fix dead ends: turn any walkable-spur (degree<2) into a wall,
# repeat until stable.
WALKABLE = set('. oPT1234-')
def deg(rows, x, y):
    n = 0
    for dx, dy in [(1,0),(-1,0),(0,1),(0,-1)]:
        if rows[y+dy][x+dx] in WALKABLE:
            n += 1
    return n

KEEP = set('oPT1234-')   # never overwrite ghost spawn / spawn / door / energizer
for _ in range(50):
    changed = False
    new = list(rows)
    for y in range(1, ROWS - 1):
        for x in range(1, COLS - 1):
            ch = rows[y][x]
            if ch not in WALKABLE: continue
            if ch in KEEP: continue
            if in_ghost_house(x, y): continue
            if deg(rows, x, y) < 2:
                new[y] = new[y][:x] + '#' + new[y][x+1:]
                changed = True
    rows = new
    if not changed: break

# Validate no dead ends in walkable cells
WALKABLE = set('. oPT1234-')
dead_ends = []
for y in range(1, ROWS - 1):
    for x in range(1, COLS - 1):
        ch = rows[y][x]
        if ch not in WALKABLE: continue
        if in_ghost_house(x, y): continue  # interior is intentionally a chamber
        deg = 0
        for dx, dy in [(1,0),(-1,0),(0,1),(0,-1)]:
            n = rows[y+dy][x+dx]
            if n in WALKABLE: deg += 1
        if deg < 2:
            dead_ends.append((x, y, ch, deg))

if dead_ends:
    print(f"// WARNING: {len(dead_ends)} dead end(s) detected:")
    for x, y, ch, n in dead_ends[:20]:
        print(f"//   ({x},{y}) = '{ch}' deg={n}")
else:
    print("// OK: zero dead ends")

print("// AUTO-GENERATED by scripts/gen_wider_maze.py")
print(f"static constexpr std::array<std::string_view, {ROWS}> CLASSIC_MAZE = {{")
for r in rows:
    print(f'    "{r}",')
print("};")
